# https://marketplace.visualstudio.com/items?itemName=humao.rest-client

@hostname = 0.0.0.0
@port = 7777
@host = {{hostname}}:{{port}}
@URL = http://{{host}}
@contentType = application/json
@blocks = blocks


###
{{URL}}

###
{{URL}}/status

### 
{{URL}}/{{blocks}}

###
POST {{URL}}/{{blocks}}
content-type: application/json

{
    "message": "mine me"
}

### 
{{URL}}/{{blocks}}/0002c7a191a6a9fded9b62145b47fb445c22379a2998da1c6c90b729b301fcc8

### 
{{URL}}/debug/db

