# https://marketplace.visualstudio.com/items?itemName=humao.rest-client

@hostname = localhost
@port = 7777
@host = {{hostname}}:{{port}}
@contentType = application/json
@blocks = blocks


###
http://{{host}}


### 
http://{{host}}/{{blocks}}

###
POST http://{{host}}/{{blocks}}
content-type: application/json

{
    "message": "Data for my block"
}

### 
http://{{host}}/{{blocks}}/3


